services:
  - type: web
    name: puppeteer-server
    env: node
    plan: free
    buildCommand: 'pnpm install'
    startCommand: 'pnpm start'
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/.cache/puppeteer/chrome/linux-127.0.6533.88/chrome-linux/chrome
