services:
  - type: web
    name: puppeteer-server
    env: node
    plan: free
    buildCommand: 'pnpm install'
    startCommand: 'pnpm start'
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
