services:
  - type: web
    name: puppeteer-server
    env: node
    buildCommand: pnpm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    scaling:
      minInstances: 1
      maxInstances: 3
    resources:
      cpu: 1x
      memory: 1024
      timeout: 300
